# mircroservice management path.
management:
  contextPath: /admin
  
endpoints:
  restart:
    enabled: true
    
# eureka server 設定
eureka:
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    serviceUrl:
      defaultZone: http://${CLOUD_CONFIG_SECURITY_USER}:${CLOUD_CONFIG_SECURITY_PASSWORD}@${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_INSTANCE_PORT}/eureka/
    healthcheck:
      enabled: false
