package com.poseitech.integration.playngo;

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.test.ConfigFileApplicationContextInitializer;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.poseitech.dao.hibernate.Paging;
import com.poseitech.integration.playngo.config.MicroserviceApplication;

/**
 * Sample junit test
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = MicroserviceApplication.class, initializers = ConfigFileApplicationContextInitializer.class)
public class SampleJunitTest {
   
   private static final Logger log = LoggerFactory.getLogger(SampleJunitTest.class);
   
   @Test
   public void testMethod()  {
      log.error("test is generated by maven archetype tool."); 
   }
}
